lidar:
  - driver:
      use_gpu: false
      source_type: 1
      lidar_udp_type:
        device_ip_address: 192.168.1.201  # 你的雷达IP
        udp_port: 2368
        ptc_port: 9347
        multicast_ip_address: 255.255.255.255
        use_ptc_connected: true
        host_ptc_port: 0
        correction_file_path: "/home/orin/calibration.csv"  # 标定文件路径
        firetimes_path: "/home/orin/firetimes.csv"          # 发射时间文件
        recv_point_cloud_timeout: -1
        ptc_connect_timeout: -1
        host_ip_address: ""
        fault_message_port: 0
        standby_mode: -1
        speed: -1
        ptc_mode: 0
        certFile: ""
        privateKeyFile: ""
        caFile: ""
      
      # public module
      use_timestamp_type: 0                 # 使用雷达时间戳
      frame_start_azimuth: 0
      thread_num: 4
      transform_flag: false
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
      fov_start: -1
      fov_end: -1
      channel_fov_filter_path: ""
      multi_fov_filter_ranges: ""
      enable_packet_loss_tool: true
      distance_correction_flag: false
      xt_spot_correction: false
      device_udp_src_port: 0
      device_fault_port: 0
      frame_frequency: 0
      default_frame_frequency: 10.0
      echo_mode_filter: 0

    ros:
      ros_frame_id: hesai_lidar
      ros_recv_packet_topic: /lidar_packets
      ros_send_packet_topic: /lidar_packets
      ros_send_point_cloud_topic: /lidar_points      # 新驱动发布的话题
      ros_send_imu_topic: /lidar_imu
      ros_send_packet_loss_topic: /lidar_packets_loss
      send_packet_ros: false
      send_point_cloud_ros: true                     # 发布点云
      send_imu_ros: true
